### ISSUE TITLE
action 连续失败两天了

### ISSUE THREAD

**Issue by BIBiBI12** [wmathor/Check_In#11]
Error: Version 3.6 with arch x64 not found

**Comment by BIBiBI12** [comment]
<img width="927" alt="截屏2022-12-02 17 42 09" src="https://user-images.githubusercontent.com/20101580/205263636-bef96763-2995-4c5e-ab45-6dcc83391f2e.png">

**Comment by wmathor** [comment]
> Error: Version 3.6 with arch x64 not found

Sorry, I've been busy with my thesis recently and haven't had time to deal with this issue

**Comment by BIBiBI12** [comment]
replace ubuntu-latest by ubuntu-20.04 in github actions .
<img width="1211" alt="截屏2022-12-05 10 25 19" src="https://user-images.githubusercontent.com/20101580/205535882-67d6e502-81b2-4592-9697-f83a3a403085.png">
