### ISSUE TITLE
修改yaml文件，可以不用一直更新chromedriver文件

### ISSUE THREAD

**Issue by cheig** [wmathor/Check_In#3]
如下，在网上找了一个github action selenium的方案
`name: selenium

#Controls when the action will run. 
on:
  #Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
  #Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install -r ./requirements.txt
    - name: Prepare Selenium
      (#https://github.com/marketplace/actions/setup-chromedriver)
      uses: nanasess/setup-chromedriver@v1.0.5
    - name: Start XVFB
      run: |
        Xvfb :99 &
    - name: Run tests
      run: python ./
    env:
      DISPLAY: :99`

**Comment by linsuk381** [comment]
快点解决吧，不能用了

**Comment by wmathor** [comment]
> 快点解决吧，不能用了

知道了知道了，今天改

**Comment by wmathor** [comment]
> 快点解决吧，不能用了

已更新
