### ISSUE TITLE
怎么适用其他网站呢

### ISSUE THREAD

**Issue by linsuk381** [wmathor/Check_In#4]
尊敬的创作者你好，我以您的脚本为蓝本，改成了其他网站，为什么却不能签到成功呢，程序已经运行成功，可是却没有签到成功，我修改的是hupu.py，您要是有空的话可以帮看一下什么原因吗？
谢谢！

**Comment by wmathor** [comment]
> 尊敬的创作者你好，我以您的脚本为蓝本，改成了其他网站，为什么却不能签到成功呢，程序已经运行成功，可是却没有签到成功，我修改的是hupu.py，您要是有空的话可以帮看一下什么原因吗？ 谢谢！

有很多原因会导致签到不成功，你得自己在本地调试，看看是没登陆上，还是什么其他原因，你总不能让我来帮你调试吧

**Comment by linsuk381** [comment]
哦哦，懂了，我昨天又仔细想了想，代码应该其没有问题的，大概率是被屏蔽了，谢谢😊
