### ISSUE TITLE
遇到一个极其离谱的chromedriver问题

### ISSUE THREAD

**Issue by zsbai** [wmathor/Check_In#5]
![2022-09-03 18 02 19](https://user-images.githubusercontent.com/62942942/188265767-c0ef3943-0522-4071-90d6-de8b1fb5124d.jpg)
![tg_image_2957880598](https://user-images.githubusercontent.com/62942942/188265774-0d334a6d-5bcb-41cc-a8a7-4a44477b5c8f.jpeg)
使用以下方法安装chromedriver
```
- name: Prepare chromedriver
      uses: nanasess/setup-chromedriver@v1

```

**Comment by wmathor** [comment]
> ![2022-09-03 18 02 19](https://user-images.githubusercontent.com/62942942/188265767-c0ef3943-0522-4071-90d6-de8b1fb5124d.jpg) ![tg_image_2957880598](https://user-images.githubusercontent.com/62942942/188265774-0d334a6d-5bcb-41cc-a8a7-4a44477b5c8f.jpeg) 使用以下方法安装chromedriver
> 
> ```
> - name: Prepare chromedriver
>       uses: nanasess/setup-chromedriver@v1
> ```

这种带缩进的写法会报语法错误
